services:
  app.shared.cqrs.command_bus.command_bus_impl:
    class: App\Shared\CQRS\CommandBus\CommandBusImpl
    arguments:
      - !service_locator
          App\Good\Command\CreateGoodCommand: '@App\Good\Command\CreateGoodHandler'
          App\Good\Command\UpdateGoodCommand: '@App\Good\Command\UpdateGoodHandler'

  App\Shared\CQRS\CommandBus\CommandBusInterface: '@app.shared.cqrs.command_bus.command_bus_impl'
